# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='debt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='kredit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
