# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_auto_20170809_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='debt',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='kredit',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
