# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_auto_20170809_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jurnal',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='transaksi',
            options={'ordering': ['id']},
        ),
    ]
