# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0002_auto_20170808_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurnal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Transaksi',
        ),
        migrations.DeleteModel(
            name='Jurnal',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
